version: "3.9"

services:
  api:
    build: ./api
    container_name: dkbldr-api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    restart: unless-stopped

  app:
    build: ./
    container_name: dkbldr-app
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    depends_on:
      - api
    restart: unless-stopped