version: "3.9"

services:
  api:
    build: 
      context: ./api
    container_name: dkbldr-api
    ports:
      - "8080:4000"
    env_file:
      - ./api/.env
    restart: unless-stopped

  app:
    build: 
      context: ./
    container_name: dkbldr-app
    ports:
      - "8081:3000"
    env_file:
      - ./.env
    depends_on:
      - api
    restart: unless-stopped