FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm i --production

COPY . .

# Utilise la variable PORT de Railway, avec 4000 comme fallback
ENV PORT=${PORT:-4000}

EXPOSE $PORT

CMD [ "node", "index.js" ]