name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  test:
    runs-on: ubuntu-latest
    environment: "production"
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    environment: "production"
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build & Push API image
        run: |
          docker build -t thibaultkine/dkbldr-api:latest ./api
          docker push thibaultkine/dkbldr-api:latest

      - name: Build & Push App
        run: |
          docker build \
            --build-arg VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --build-arg VITE_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_KEY }} \
            -t thibaultkine/dkbldr-app:latest ./
          docker push thibaultkine/dkbldr-app:latest


      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Add Railway to PATH
        run: echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Redeploy API
        run: railway redeploy --service dkbldr-api --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Redeploy App
        run: railway redeploy --service dkbldr-app --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

