name: Deploy on self-hosted runner (Windows x64)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: "production"
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build API Docker image
        run: docker build -t dkbldr-api:latest ./api

      - name: Push image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker tag dkbldr-api:latest ${{ secrets.DOCKER_USER }}/dkbldr-api:latest
          docker push ${{ secrets.DOCKER_USER }}/dkbldr-api:latest
