name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: quick check
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "SUPABASE_URL is empty"
          else
            echo "SUPABASE_URL is set (length=$(echo -n $SUPABASE_URL | wc -c))"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./api
        run: npm i

      - name: Run tests
        run: npm run test
        working-directory: ./api